name : Build

permissions:
  id-token: write
  contents: write

env:
  BuildConfiguration: Release
  DockerFilePath: './src/RoyalLifeSavings/'
  dotnet-version: 6.0.x
  
on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request: 
    branches:
    - main
    
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{env.dotnet-version }}
        
  
    - name: Build Project
      working-directory: './src'
      run: dotnet build --configuration ${{ env.BuildConfiguration }}
    - name: Run Tests
      working-directory: './src'
      run: dotnet test --configuration ${{ env.BuildConfiguration }} --logger GitHubActions
        
  
  dockerise:
    if: github.ref == 'refs/heads/main'
    name: Containerise and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID}}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}   
      - name: ACR Login
        run: az acr login --name ${{ vars.AZURE_CONTAINER_REGISTRY }}          
      - name: Build and Push to Docker
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.AZURE_CONTAINER_IMAGE_NAME }}:${{ github.run_number }}
            ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.AZURE_CONTAINER_IMAGE_NAME }}:latest
          context: ${{ env.DockerFilePath }}
          file: ${{ env.DockerFilePath }}/Dockerfile
      - name: Tag Release
        run: |
          git tag ${{ github.run_number }}
          git push origin ${{ github.run_number }}          
  devdeploy:
    name: Dev Deploy
    needs: dockerise
    uses: .github/workflows/deploy.yaml
    with:
      containertag: ${{ github.run_number }}
      environment: 'Dev'
    secrets: inherit
